-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE TABLE public.meiban_info (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  booth_id UUID REFERENCES public.exhibitor_booths(id) ON DELETE SET NULL,
  company_name_cn TEXT NOT NULL,
  company_name_en TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE public.meiban_info ENABLE ROW LEVEL SECURITY;

CREATE POLICY "所有人可查看楣板信息" ON public.meiban_info FOR SELECT USING (true);
CREATE POLICY "所有人可创建楣板信息" ON public.meiban_info FOR INSERT WITH CHECK (true);
CREATE POLICY "所有人可更新楣板信息" ON public.meiban_info FOR UPDATE USING (true);