-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

ALTER TABLE public.invoice_info ALTER COLUMN booth_id DROP NOT NULL;

ALTER TABLE public.invoice_info ALTER COLUMN user_id DROP NOT NULL;

UPDATE public.invoice_info SET booth_id = NULL WHERE booth_id IS NOT NULL;