-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

DROP POLICY IF EXISTS "审图员可以查看所有资料" ON public.profiles;
DROP POLICY IF EXISTS "管理员可以查看所有资料" ON public.profiles;
DROP POLICY IF EXISTS "管理员可以更新所有资料" ON public.profiles;
DROP FUNCTION IF EXISTS public.get_current_user_role();

-- profiles 表的普通用户访问由 auth.uid() = id 策略控制。
-- 不再使用自引用函数或额外的 SELECT 来判断管理员/审图员权限，避免递归问题。