-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE OR REPLACE FUNCTION public.get_current_user_role()
RETURNS TEXT
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT role::TEXT FROM public.profiles WHERE id = auth.uid();
$$;

DROP POLICY IF EXISTS "审图员可以查看所有资料" ON public.profiles;
DROP POLICY IF EXISTS "管理员可以查看所有资料" ON public.profiles;
DROP POLICY IF EXISTS "管理员可以更新所有资料" ON public.profiles;

CREATE POLICY "审图员可以查看所有资料" ON public.profiles
FOR SELECT USING (public.get_current_user_role() = 'reviewer');

CREATE POLICY "管理员可以查看所有资料" ON public.profiles
FOR SELECT USING (public.get_current_user_role() = 'admin');

CREATE POLICY "管理员可以更新所有资料" ON public.profiles
FOR UPDATE USING (public.get_current_user_role() = 'admin');