-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 创建 payment-vouchers 存储桶
INSERT INTO storage.buckets (id, name, public)
VALUES ('payment-vouchers', 'payment-vouchers', true)
ON CONFLICT (id) DO NOTHING;

-- 创建存储桶的 RLS 策略
CREATE POLICY "所有人可上传付费凭证" ON storage.objects
  FOR INSERT WITH CHECK (bucket_id = 'payment-vouchers');

CREATE POLICY "所有人可查看付费凭证" ON storage.objects
  FOR SELECT USING (bucket_id = 'payment-vouchers');

CREATE POLICY "所有人可更新付费凭证" ON storage.objects
  FOR UPDATE USING (bucket_id = 'payment-vouchers');