-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 删除现有的 profiles 表管理策略，以避免通过 self-select 检查权限造成的复杂性。
DROP POLICY IF EXISTS "审图员可以查看展商资料" ON public.profiles;
DROP POLICY IF EXISTS "管理员可以查看所有用户资料" ON public.profiles;
DROP POLICY IF EXISTS "管理员可以更新所有用户资料" ON public.profiles;

-- 统一使用 auth.uid() = id 作为普通用户的 RLS 访问控制。
-- 如果需要管理员/审图员额外权限，建议使用独立的 JWT 自定义声明或单独的授权表。
