-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE TABLE IF NOT EXISTS qualification_documents (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  booth_number TEXT NOT NULL UNIQUE,
  business_license_urls TEXT[] DEFAULT '{}',
  application_letter_urls TEXT[] DEFAULT '{}',
  entrustment_letter_urls TEXT[] DEFAULT '{}',
  safety_responsibility_urls TEXT[] DEFAULT '{}',
  volume_commitment_urls TEXT[] DEFAULT '{}',
  violation_handling_urls TEXT[] DEFAULT '{}',
  insurance_policy_urls TEXT[] DEFAULT '{}',
  equipment_rental_urls TEXT[] DEFAULT '{}',
  electrician_certificate_urls TEXT[] DEFAULT '{}',
  is_submitted BOOLEAN DEFAULT FALSE,
  submitted_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE qualification_documents ENABLE ROW LEVEL SECURITY;

CREATE POLICY "所有人可查看资质文件" ON qualification_documents FOR SELECT USING (true);
CREATE POLICY "所有人可创建资质文件" ON qualification_documents FOR INSERT WITH CHECK (true);
CREATE POLICY "所有人可更新资质文件" ON qualification_documents FOR UPDATE USING (true);