-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

ALTER TABLE public.invoice_info ADD COLUMN IF NOT EXISTS booth_number TEXT;

CREATE INDEX IF NOT EXISTS idx_invoice_info_booth_number ON public.invoice_info(booth_number);

UPDATE public.invoice_info SET booth_number = booth_id::text WHERE booth_number IS NULL;