-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

UPDATE auth.users SET encrypted_password = crypt('90F11', gen_salt('bf')) WHERE email = '11100000000@review.local';