-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

INSERT INTO storage.buckets (id, name, public)
VALUES ('qualification-documents', 'qualification-documents', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "所有人可上传资质文件" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'qualification-documents');
CREATE POLICY "所有人可查看资质文件" ON storage.objects FOR SELECT USING (bucket_id = 'qualification-documents');
CREATE POLICY "所有人可删除资质文件" ON storage.objects FOR DELETE USING (bucket_id = 'qualification-documents');