-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 为 exhibitor_booths 表添加 user_id 唯一约束
ALTER TABLE public.exhibitor_booths 
ADD CONSTRAINT exhibitor_booths_user_id_unique 
UNIQUE (user_id);