-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE TABLE IF NOT EXISTS booth_fixed_fees (
  id SERIAL PRIMARY KEY,
  booth_id UUID NOT NULL REFERENCES exhibitor_booths(id) ON DELETE CASCADE,
  management_fee_paid BOOLEAN DEFAULT false,
  deposit_paid BOOLEAN DEFAULT false,
  height_review_fee_paid BOOLEAN DEFAULT false,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  UNIQUE(booth_id)
);

ALTER TABLE booth_fixed_fees ENABLE ROW LEVEL SECURITY;

-- 允许所有人查看
CREATE POLICY "所有人可查看固定费用缴费状态" ON booth_fixed_fees FOR SELECT USING (true);

-- 允许管理员和审图员更新
CREATE POLICY "管理员和审图员可更新固定费用" ON booth_fixed_fees FOR ALL USING (
  EXISTS (
    SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('admin', 'reviewer')
  )
);