-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 删除现有的 profiles 表 RLS 策略
DROP POLICY IF EXISTS "审图员可以查看展商资料" ON public.profiles;
DROP POLICY IF EXISTS "管理员可以查看所有用户资料" ON public.profiles;
DROP POLICY IF EXISTS "管理员可以更新所有用户资料" ON public.profiles;

-- 重新创建策略：审图员可以查看所有资料
CREATE POLICY "审图员可以查看所有资料" ON public.profiles
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE id = auth.uid() AND role = 'reviewer'
    )
  );

-- 重新创建策略：管理员可以查看所有资料
CREATE POLICY "管理员可以查看所有资料" ON public.profiles
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- 重新创建策略：管理员可以更新所有资料
CREATE POLICY "管理员可以更新所有资料" ON public.profiles
  FOR UPDATE USING (
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE id = auth.uid() AND role = 'admin'
    )
  );