-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

-- 为 exhibitor_booths 表添加 RLS 策略
ALTER TABLE public.exhibitor_booths ENABLE ROW LEVEL SECURITY;

-- 展商可以查看自己的展位信息
CREATE POLICY "展商可以查看自己的展位信息" ON public.exhibitor_booths
  FOR SELECT USING (auth.uid() = user_id);

-- 展商可以更新自己的展位信息
CREATE POLICY "展商可以更新自己的展位信息" ON public.exhibitor_booths
  FOR UPDATE USING (auth.uid() = user_id);

-- 管理员可以查看所有展位信息
CREATE POLICY "管理员可以查看所有展位信息" ON public.exhibitor_booths
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- 管理员可以管理所有展位信息
CREATE POLICY "管理员可以管理所有展位信息" ON public.exhibitor_booths
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

-- 审图员可以查看所有展位信息
CREATE POLICY "审图员可以查看所有展位信息" ON public.exhibitor_booths
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE id = auth.uid() AND role = 'reviewer'
    )
  );

-- 审图员可以管理展位信息
CREATE POLICY "审图员可以管理展位信息" ON public.exhibitor_booths
  FOR ALL USING (
    EXISTS (
      SELECT 1 FROM public.profiles 
      WHERE id = auth.uid() AND role = 'reviewer'
    )
  );

-- 创建安全定义函数用于检查角色
CREATE OR REPLACE FUNCTION public.has_role(_user_id UUID, _role public.user_role)
RETURNS BOOLEAN
LANGUAGE SQL STABLE
SECURITY DEFINER SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = _user_id AND role = _role
  )
$$;