-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- （已增加幂等处理：类型/表已存在或重复执行 Supabase SQL Editor 时不报错）
-- ============================================

-- 创建角色枚举类型（已存在则跳过）
DO $$
BEGIN
  CREATE TYPE public.user_role AS ENUM ('admin', 'reviewer', 'standard_exhibitor', 'custom_exhibitor');
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- 创建用户资料表
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  username TEXT UNIQUE NOT NULL,
  display_name TEXT,
  role public.user_role NOT NULL DEFAULT 'standard_exhibitor',
  phone TEXT,
  avatar_url TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 启用 RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- RLS 策略（先删后建，避免重复执行报错）
DROP POLICY IF EXISTS "用户可以查看自己的资料" ON public.profiles;
CREATE POLICY "用户可以查看自己的资料" ON public.profiles
  FOR SELECT USING (auth.uid() = id);

DROP POLICY IF EXISTS "用户可以更新自己的资料" ON public.profiles;
CREATE POLICY "用户可以更新自己的资料" ON public.profiles
  FOR UPDATE USING (auth.uid() = id);

DROP POLICY IF EXISTS "用户可以插入自己的资料" ON public.profiles;
CREATE POLICY "用户可以插入自己的资料" ON public.profiles
  FOR INSERT WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "管理员可以查看所有用户资料" ON public.profiles;
CREATE POLICY "管理员可以查看所有用户资料" ON public.profiles
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

DROP POLICY IF EXISTS "管理员可以更新所有用户资料" ON public.profiles;
CREATE POLICY "管理员可以更新所有用户资料" ON public.profiles
  FOR UPDATE USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND role = 'admin'
    )
  );

DROP POLICY IF EXISTS "审图员可以查看展商资料" ON public.profiles;
CREATE POLICY "审图员可以查看展商资料" ON public.profiles
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE id = auth.uid() AND role = 'reviewer'
    ) AND role IN ('standard_exhibitor', 'custom_exhibitor')
  );

-- 创建自动处理新用户的触发器函数
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = public, auth
AS $$
BEGIN
  -- 自动确认用户邮箱
  UPDATE auth.users SET email_confirmed_at = NOW() WHERE id = new.id;

  -- 创建用户资料
  INSERT INTO public.profiles (id, username, display_name, role, phone, avatar_url)
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data ->> 'username', split_part(new.email, '@', 1)),
    new.raw_user_meta_data ->> 'display_name',
    COALESCE((new.raw_user_meta_data ->> 'role')::public.user_role, 'standard_exhibitor'),
    new.raw_user_meta_data ->> 'phone',
    new.raw_user_meta_data ->> 'avatar_url'
  );
  RETURN new;
END;
$$;

-- 创建触发器（已存在则先删再建）
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
