-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

ALTER TABLE qualification_documents 
ADD COLUMN IF NOT EXISTS business_license_status TEXT DEFAULT 'pending',
ADD COLUMN IF NOT EXISTS application_letter_status TEXT DEFAULT 'pending',
ADD COLUMN IF NOT EXISTS entrustment_letter_status TEXT DEFAULT 'pending',
ADD COLUMN IF NOT EXISTS safety_responsibility_status TEXT DEFAULT 'pending',
ADD COLUMN IF NOT EXISTS volume_commitment_status TEXT DEFAULT 'pending',
ADD COLUMN IF NOT EXISTS violation_handling_status TEXT DEFAULT 'pending',
ADD COLUMN IF NOT EXISTS insurance_policy_status TEXT DEFAULT 'pending',
ADD COLUMN IF NOT EXISTS equipment_rental_status TEXT DEFAULT 'pending',
ADD COLUMN IF NOT EXISTS electrician_certificate_status TEXT DEFAULT 'pending',
ADD COLUMN IF NOT EXISTS business_license_comment TEXT,
ADD COLUMN IF NOT EXISTS application_letter_comment TEXT,
ADD COLUMN IF NOT EXISTS entrustment_letter_comment TEXT,
ADD COLUMN IF NOT EXISTS safety_responsibility_comment TEXT,
ADD COLUMN IF NOT EXISTS volume_commitment_comment TEXT,
ADD COLUMN IF NOT EXISTS violation_handling_comment TEXT,
ADD COLUMN IF NOT EXISTS insurance_policy_comment TEXT,
ADD COLUMN IF NOT EXISTS equipment_rental_comment TEXT,
ADD COLUMN IF NOT EXISTS electrician_certificate_comment TEXT,
ADD COLUMN IF NOT EXISTS review_round INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS last_reviewed_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS reviewed_by TEXT;