-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE TABLE IF NOT EXISTS public.invoice_info (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  booth_id UUID NOT NULL REFERENCES public.exhibitor_booths(id) ON DELETE CASCADE,
  company_name TEXT,
  tax_id TEXT,
  address TEXT,
  phone TEXT,
  bank_name TEXT,
  bank_account TEXT,
  payment_voucher_url TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE public.invoice_info ENABLE ROW LEVEL SECURITY;

CREATE POLICY "所有人可查看开票信息" ON public.invoice_info
  FOR SELECT USING (true);

CREATE POLICY "所有人可创建开票信息" ON public.invoice_info
  FOR INSERT WITH CHECK (true);

CREATE POLICY "所有人可更新开票信息" ON public.invoice_info
  FOR UPDATE USING (true);

CREATE INDEX idx_invoice_info_booth_id ON public.invoice_info(booth_id);
CREATE INDEX idx_invoice_info_user_id ON public.invoice_info(user_id);