-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE TABLE public.exhibitor_applications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  booth_id UUID REFERENCES public.exhibitor_booths(id),
  category VARCHAR(50) NOT NULL,
  content JSONB NOT NULL DEFAULT '[]',
  status VARCHAR(20) DEFAULT 'pending',
  payment_status VARCHAR(20) DEFAULT 'unpaid',
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW(),
  reviewer_notes TEXT
);

CREATE INDEX idx_applications_user_id ON public.exhibitor_applications(user_id);
CREATE INDEX idx_applications_category ON public.exhibitor_applications(category);
CREATE INDEX idx_applications_status ON public.exhibitor_applications(status);
CREATE INDEX idx_applications_payment ON public.exhibitor_applications(payment_status);

ALTER TABLE public.exhibitor_applications ENABLE ROW LEVEL SECURITY;

CREATE POLICY "审图员可查看所有申报" ON public.exhibitor_applications
FOR SELECT USING (public.get_current_user_role() IN ('admin', 'reviewer'));

CREATE POLICY "审图员可更新申报" ON public.exhibitor_applications
FOR UPDATE USING (public.get_current_user_role() IN ('admin', 'reviewer'));

CREATE POLICY "展商可查看自己的申报" ON public.exhibitor_applications
FOR SELECT USING (user_id = auth.uid());

CREATE POLICY "展商可创建自己的申报" ON public.exhibitor_applications
FOR INSERT WITH CHECK (user_id = auth.uid());