-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE TABLE IF NOT EXISTS public.drawing_history (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  booth_number TEXT NOT NULL,
  drawing_type TEXT NOT NULL,
  file_url TEXT NOT NULL,
  review_round INTEGER DEFAULT 0,
  uploaded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE public.drawing_history ENABLE ROW LEVEL SECURITY;

CREATE POLICY "所有人可查看图纸历史" ON public.drawing_history
FOR SELECT USING (true);

CREATE POLICY "所有人可添加图纸历史" ON public.drawing_history
FOR INSERT WITH CHECK (true);