-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE TABLE IF NOT EXISTS fee_rules (
  id SERIAL PRIMARY KEY,
  management_fee_per_sqm DECIMAL(10, 2) NOT NULL DEFAULT 0,
  deposit_0_50 DECIMAL(10, 2) NOT NULL DEFAULT 0,
  deposit_51_100 DECIMAL(10, 2) NOT NULL DEFAULT 0,
  deposit_over_100 DECIMAL(10, 2) NOT NULL DEFAULT 0,
  height_review_fee DECIMAL(10, 2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

-- 插入默认配置
INSERT INTO fee_rules (management_fee_per_sqm, deposit_0_50, deposit_51_100, deposit_over_100, height_review_fee)
VALUES (0, 0, 0, 0, 0)
ON CONFLICT DO NOTHING;

ALTER TABLE fee_rules ENABLE ROW LEVEL SECURITY;

-- 允许所有人查看
CREATE POLICY "所有人可查看收费规则" ON fee_rules FOR SELECT USING (true);

-- 仅管理员可修改
CREATE POLICY "仅管理员可修改收费规则" ON fee_rules FOR UPDATE USING (
  EXISTS (
    SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'
  )
);

CREATE POLICY "仅管理员可插入收费规则" ON fee_rules FOR INSERT WITH CHECK (
  EXISTS (
    SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'
  )
);