-- ============================================
-- 此文件由云服务自动生成，请勿手动修改
-- This file is auto-generated by meoo cloud service, DO NOT MODIFY
-- ============================================

CREATE TABLE IF NOT EXISTS public.builder_info (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  booth_number TEXT NOT NULL UNIQUE,
  builder_name TEXT,
  contact_name TEXT,
  contact_phone TEXT,
  contact_email TEXT,
  created_at TIMESTAMP DEFAULT NOW(),
  updated_at TIMESTAMP DEFAULT NOW()
);

ALTER TABLE public.builder_info ENABLE ROW LEVEL SECURITY;

CREATE POLICY "所有人可查看搭建商信息" ON public.builder_info
  FOR SELECT USING (true);

CREATE POLICY "所有人可创建搭建商信息" ON public.builder_info
  FOR INSERT WITH CHECK (true);

CREATE POLICY "所有人可更新搭建商信息" ON public.builder_info
  FOR UPDATE USING (true);

CREATE INDEX idx_builder_info_booth_number ON public.builder_info(booth_number);